codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch:
      default:
        target: 0%
        threshold: 0%
        base: auto
        informational: true
    project:
      default:
        target: 0%
        threshold: 0%
        base: auto
        informational: true
  precision: 2
  round: down
  range: "0...100"
