[package]
name = "iced-x86-fzgt"
version = "0.1.0"
authors = ["iced project and contributors <https://github.com/icedland>"]
license = "MIT"
description = "Test FuzzerGen output"
edition = "2018"
publish = false

[dependencies]
structopt = "0.3.15"

[dependencies.iced-x86]
path = "../iced-x86"
